### PR TITLE
Use alpha for stake in neuron info

### LINKED ISSUE #879: Inconsistent stake numbers across RPCs
NeuronInfo RPC currently reports stake values like follows:

```
NeuronInfoLite(hotkey='5DfZR9qRhv2C7JT2fxJ2dLUX1QPZYQwwA5D3NGGUBW3RLsXW', coldkey='5CvaAT12X8nJBczNDm6QoqFgDrsWhtzkr4F5wdnD8yYz326C', uid=0, netuid=2, active=True, stake=τ 34.8542, stake_dict={'5CvaAT12X8nJBczNDm6QoqFgDrsWhtzkr4F5wdnD8yYz326C': τ 34.8542}, total_stake=τ 34.8542, rank=0.0, emission=28.210070956, incentive=0.0, consensus=0.0, trust=0.0, validator_trust=0.0, dividends=0.0, last_update=181, validator_permit=True, prometheus_info=PrometheusInfo(block=0, version=0, ip='0.0.0.0', port=0, ip_type=0), axon_info=AxonInfo(version=0, ip='0.0.0.0', port=0, ip_type=0, hotkey='5DfZR9qRhv2C7JT2fxJ2dLUX1QPZYQwwA5D3NGGUBW3RLsXW', coldkey='5CvaAT12X8nJBczNDm6QoqFgDrsWhtzkr4F5wdnD8yYz326C', protocol=0, placeholder1=0, placeholder2=0), pruning_score=65535, is_null=False)
```

which is inconsistent with StakeInfo RPC. This can be reproduced with btcli by running:

```bash
btcli st list
btcli w balance
btcli w inspect
```

Image
Image
Image

### PR DESCRIPTION
**Pull request by ales-otf**
## Description

This PR fixes inconsistency issues related to staking values returned by RPC's `NeuronInfoRuntimeApi` and `StakeInfoRuntimeApi`.

Getters for the `stake` values are added to `NeuronInfo`, `NeuronInfoLite` and `StakeInfo`, because there is no other way to test this values in the integration tests.

## Related Issue(s)

- Closes #879

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional Notes

It would be better to introduce different types for TAO and Alpha balances, so these kinds of errors would be discoverable at the compilation time (#887).

Also, to prevent possible inconsistencies between `NeuronInfo` and `NeuronInfoLite` it would be better to make `NeuronInfoLite` a part of `NeuronInfo`, instead of duplicating information between them.

Allowing unit/module tests would help with private API testing. In case the module tests are not possible, another option could be a cargo feature, which would make API dedicated to tests being compiled for tests only (`#[cfg(test)]` doesn't work for the integration tests).

### CODE REVIEW

**Comment by camfairchild** [comment]
The reason we use `stake_weight` is because this is what miners need to prioritize Validator requests appropriately. 
This value directly impacts a miner's emission, versus the alpha entry, which is not meaningful.

**Comment by ales-otf** [comment]
> The reason we use `stake_weight` is because this is what miners need to prioritize Validator requests appropriately. This value directly impacts a miner's emission, versus the alpha entry, which is not meaningful.

But in `NeuronInfoLite` the value was from `Stake` storage, while in `NeuronInfo` from `StakeWeight`, and in `StakeInfo` it's `Alpha`. Which one is true then?

Or is it `StakeWeight` only in `NeuronInfo`?

**Comment by ales-otf** [comment]
> The reason we use `stake_weight` is because this is what miners need to prioritize Validator requests appropriately. This value directly impacts a miner's emission, versus the alpha entry, which is not meaningful.

Can we add additional field `stake_weight` to `NeuronInfo` and `NeuronInfoLite`? Also, if we can, could we make `NeuronInfoLite` being a part of `NeuronInfo` to omit the duplication and inconsistencies?

**Comment by camfairchild** [comment]
> > The reason we use `stake_weight` is because this is what miners need to prioritize Validator requests appropriately. This value directly impacts a miner's emission, versus the alpha entry, which is not meaningful.
> 
> But in `NeuronInfoLite` the value was from `Stake` storage, while in `NeuronInfo` from `StakeWeight`, and in `StakeInfo` it's `Alpha`. Which one is true then?
> 
> Or is it `StakeWeight` only in `NeuronInfo`?

I believe this change is attempting to keep the same struct type-wise, while changing the value to be as meaningful to the client as it was.

When we didn't have the `Alpha` map, the only value that mattered in this context was the `Stake` map. But now we use a calculated `stake_weight` to mean the same thing. So this is what should be returned

**Comment by camfairchild** [comment]
> Can we add additional field `stake_weight` to `NeuronInfo` and `NeuronInfoLite`? 

We could, but the big issue with this is we don't have proper versioning set up for the RuntimeAPIs and RPCs. So this will break any clients that rely on this API (many).

**Comment by gztensor** [comment]
@camfairchild , we have `get_global_for_hotkey_and_coldkey` and `get_global_for_hotkey_and_coldey_on_subnet` methods. Can we just use them in `StakeInfo` and `NeuronInfo` respectively?

**Comment by ales-otf** [comment]
Closing, as `NeuronInfo::stake` should be `StakeWeight` and the difference between `StakeInfo::stake` and `NeuronInfo::stake` is expected and should be handled on the client's side.

To fix the inconsistency between `NeuronInfo::stake` and `NeuronInfoLite::stake` a separate [PR](https://github.com/opentensor/subtensor/pull/896) is open.

**Pull request closed without merging**
