### PR TITLE
Removing from the "main" branch the doc to run subtensor locally

### PR DESCRIPTION
**Pull request by rajkaramchedu**
As per this Discord thread: https://discord.com/channels/799672011265015819/1260678915186495509

Docs issue: https://github.com/opentensor/developer-docs/issues/221

## Related Issue(s)

- Closes #[issue number]

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

### CODE REVIEW

**Comment by rajkaramchedu** [comment]
For Documentation change, what should be the label? Right now it is failing the CI checks.

**Review by distributedstatemachine — APPROVED** [review]

**Comment by sam0x17** [comment]
> For Documentation change, what should be the label? Right now it is failing the CI checks.

Once something else merges that bumps the spec version this should pass the finney deploy check. E2E tests are on the fritz for everyone at the moment so that is going to keep failing until that is fixed by someone. If this is time sensitive we should get @garrett-opentensor to force merge it

edit: I just merged in main and it will prob pass now

**Review by sam0x17 — APPROVED** [review]

**Review by open-junius — APPROVED** [review]

**Comment by sam0x17** [comment]
I'll push a commit and see if I can get it merge-able real quick

**Comment by rajkaramchedu** [comment]
> > For Documentation change, what should be the label? Right now it is failing the CI checks.
> 
> Once something else merges that bumps the spec version this should pass the finney deploy check. E2E tests are on the fritz for everyone at the moment so that is going to keep failing until that is fixed by someone. If this is time sensitive we should get @garrett-opentensor to force merge it
> 
> edit: I just merged in main and it will prob pass now

This and #657 are both valid. This is a little bit pressing, because I want to remove the doc from here asap. The #657 can wait. Perhaps @garrett-opentensor you can force merge this? Thanks! (Context: This is a part of consolidating subtensor node installation docs into docs.bittensor.com versions (to get to single source of truth for docs).

**Pull request merged**
