### PR TITLE
hotfix(docker): Use raw_testspec for test nodes

### PR DESCRIPTION
**Pull request by birkskyum**
See https://github.com/opentensor/subtensor/pull/325

### CODE REVIEW

**Review by open-junius — APPROVED** [review]
LGTM! thanks

**Comment by birkskyum** [comment]
@open-junius , anything holding this?

After this PR it would be great if someone could also have a look at the --ws and --rpc flags if they are all correct, because it seems there have been some changes lately removing some of the --ws flags in favor of --rpc

**Comment by open-junius** [comment]
> @open-junius , anything holding this?
> 
> After this PR it would be great if someone could also have a look at the --ws and --rpc flags if they are all correct, because it seems there have been some changes lately removing some of the --ws flags in favor of --rpc

You are right, we need remove the --ws after upgraded to polkadot 1.0. And other like --ws-max-connections

**Comment by birkskyum** [comment]
@open-junius , would you like me to apply that to this pr, or can it be done after?

**Comment by open-junius** [comment]
> @open-junius , would you like me to apply that to this pr, or can it be done after?

We can do it after upgrade the master branch to polkadot 1.0. the doc is for master. You can create new one after upgrade, and thanks for you update and verify the doc

**Comment by birkskyum** [comment]
@open-junius  Is the master on polkadot 1 now, or where can it be tracked? I know the testchain is on v1, and this is a testchain-only fix

**Comment by birkskyum** [comment]
anything holding this?

**Pull request closed without merging**
